# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"  
    config.vm.provider "virtualbox" do |v|
      v.memory = 256
      v.cpus = 1
    end
  
    config.vm.define "nfsSRV" do |nfss|
      nfss.vm.network "private_network", ip: "192.168.56.10", virtualbox__intnet: "net1"
      nfss.vm.hostname = "nfsSRV"
      nfss.vm.provision "shell", inline: <<-SHELL
            echo -e "\n\n-----------------------------------------------"
            echo -e "\nСтавим необходимые компоненты nfs-utils на Серверную часть"
            yum install -y nfs-utils
            echo -e "\n\n-----------------------------------------------"
            echo -e "\nВключаем межсетевой экран и добавляем его в автозапуск"
            systemctl enable firewalld.service --now
            echo -e "\nДобавление правила для службы nfs3"
            firewall-cmd --permanent --add-service="nfs3"
            echo -e "\nДобавление правила для службы rpc-bind"
            firewall-cmd --permanent --add-service="rpc-bind"
            echo -e "\nДобавление правила для службы mountd"
            firewall-cmd --permanent --add-service="mountd"
            firewall-cmd --reload
            echo -e "\n\n-----------------------------------------------"
            echo -e "\nВключаем НФС и добавляем кго в автозапуск"
            systemctl enable nfs --now
            echo -e "\n\n-----------------------------------------------"
            echo -e "\nСоздаем и настраиваем необходимые диреткории /srv/share/upload"
            mkdir -p /srv/share/upload
            chown -R nfsnobody:nfsnobody /srv/share
            chmod 0777 /srv/share/upload
            echo -e "\n\n-----------------------------------------------"
            echo -e "\nВ итоге получаем:"
            ls -la /srv/share/
            echo -e "\n\n-----------------------------------------------"
            echo -e "\nНастраиваем доступ к шаре /srv/share нашему планируемому клиенту"
            echo "/srv/share 192.168.56.11/32(rw,sync,root_squash)" >> /etc/exports
            exportfs -r
            exportfs
            echo -e "\n\n-----------------------------------------------"
            echo -e "\nСерверную часть подготовили приступаем к клиенту"
          SHELL
    end
  
    config.vm.define "nfsCL" do |nfsc|
      nfsc.vm.network "private_network", ip: "192.168.56.11", virtualbox__intnet: "net1"
      nfsc.vm.hostname = "nfsCL"
      nfsc.vm.provision "shell", inline: <<-SHELL
            echo -e "\n\n-----------------------------------------------"
            echo -e "\nСтавим необходимые компоненты nfs-utils на Клиентскую часть"
            yum install -y nfs-utils
            echo -e "\n\n-----------------------------------------------"
            echo -e "\nВключаем межсетевой экран и добавляем его в автозапуск"
            systemctl enable firewalld.service --now
            echo -e "\n\n-----------------------------------------------"
            echo -e "\nДелаем автомонтирование НФСшары с необходимыми параметрами и перечитываем службы с последующей перезагрузкой"
            echo "192.168.56.10:/srv/share/ /mnt nfs vers=3,proto=udp,noauto,x-systemd.automount 0 0" >> /etc/fstab
            systemctl daemon-reload
            systemctl restart remote-fs.target
            echo -e "\n\n-----------------------------------------------"
            echo -e "\Проверим доступ на запись, для этого создадим там файл с именем testfile"
            touch /mnt/upload/testfile
            echo -e "\n\n-----------------------------------------------"
            echo -e "\nls -la /mnt"
            ls -la /mnt
            echo -e "\n\n-----------------------------------------------"
            echo -e "\nls -la /mnt/upload"
            ls -la /mnt/upload
            echo -e "\nВсе готово, спасибо за проверку"
          SHELL
    end

    
  
  end
